import { collection, addDoc } from 'firebase/firestore';
import { db } from '../config/firebase';

const alunos = [
{ nome: 'Aline Di Martini Dondoni Nascimento', turma: '6º ano' },
{ nome: 'Ana Amélia Meireles d\'Assunção', turma: '6º ano' },
{ nome: 'Ana Luíza Canuto Silva', turma: '6º ano' },
{ nome: 'Antônio Curvelo Henrique Rodrigues', turma: '6º ano' },
{ nome: 'Augusto Fantoni Tallon', turma: '6º ano' },
{ nome: 'Cecília Lazarini Machado', turma: '6º ano' },
{ nome: 'Claire Lopes Barbosa', turma: '6º ano' },
{ nome: 'Daniela Saboia Macharete Trally', turma: '6º ano' },
{ nome: 'Derik de Souza Lima', turma: '6º ano' },
{ nome: 'Eduardo Neres Rodrigues', turma: '6º ano' },
{ nome: 'Eva Lessa de Moraes', turma: '6º ano' },
{ nome: 'Gabriel Cordeiro Pontes', turma: '6º ano' },
{ nome: 'Heitor Coutinho Machado', turma: '6º ano' },
{ nome: 'Henrique Maia Pereira de Freitas', turma: '6º ano' },
{ nome: 'Ísis Oliveira Figueiredo', turma: '6º ano' },
{ nome: 'João Gabriel Andrade Slipack', turma: '6º ano' },
{ nome: 'João Vitor Chagas Faria', turma: '6º ano' },
{ nome: 'Lavínia Figueiredo Cardoso', turma: '6º ano' },
{ nome: 'Letícia Neves de Souza Toledo', turma: '6º ano' },
{ nome: 'Lucas Ribeiro dos Santos', turma: '6º ano' },
{ nome: 'Luiz Fellipe Tavares Gomes', turma: '6º ano' },
{ nome: 'Manoela Drehmer Pinzon', turma: '6º ano' },
{ nome: 'Miguel Koehler Isidoro', turma: '6º ano' },
{ nome: 'Nícolas Arthur Corrêa Sanz', turma: '6º ano' },
{ nome: 'Pedro Citeli Diniz', turma: '6º ano' },
{ nome: 'Pedro Henrique Simões Magalhães', turma: '6º ano' },
{ nome: 'Pedro Oliveira Freitas', turma: '6º ano' },
{ nome: 'Théo José de Alencar Sarmanho', turma: '6º ano' },
{ nome: 'Victor Fabiano Oliveira Penna', turma: '6º ano' },

{ nome: 'Caio Henrique Albuquerque de Souza', turma: '7º ano' },
{ nome: 'Daniel Reis Guimarães', turma: '7º ano' },
{ nome: 'Fernanda Cezimbra Rigon', turma: '7º ano' },
{ nome: 'Giovanna Esterque Barbosa', turma: '7º ano' },
{ nome: 'Helena Kalil Magalhães Silva', turma: '7º ano' },
{ nome: 'Helena Marques Teixeira', turma: '7º ano' },
{ nome: 'Helena Santos Leitão', turma: '7º ano' },
{ nome: 'Iago de Souza Ribeiro Paschoal', turma: '7º ano' },
{ nome: 'Júlia dos Reis Ferreira', turma: '7º ano' },
{ nome: 'Lara Barcelos da Cruz dos Anjos Fernandes', turma: '7º ano' },
{ nome: 'Lázaro Ismério de Figueiredo Cosendey Alves', turma: '7º ano' },
{ nome: 'Leandra Manuela dos Santos Cândido', turma: '7º ano' },
{ nome: 'Letícia Vasconcelos Pereira', turma: '7º ano' },
{ nome: 'Luna Silmarils Almeida Osório', turma: '7º ano' },
{ nome: 'Maria Flor Guimarães de Almeida', turma: '7º ano' },
{ nome: 'Maria Lua Torres da Mota', turma: '7º ano' },
{ nome: 'Natasha Rosa e Silva B. Starling', turma: '7º ano' },
{ nome: 'Rafaela Simão Martins', turma: '7º ano' },
{ nome: 'Rodrigo de Queiroz Ramos Filho', turma: '7º ano' },
{ nome: 'Sofia Farias Firmo', turma: '7º ano' },
{ nome: 'Théo Santos Guimarães', turma: '7º ano' },
{ nome: 'Thomas Pereira Antunes', turma: '7º ano' },

{ nome: 'Ana Clara Grassano Branco', turma: '8º ano' },
{ nome: 'Ana Luíza Tavares da Costa', turma: '8º ano' },
{ nome: 'Caio Dórigo', turma: '8º ano' },
{ nome: 'Duanne Barra Moreira', turma: '8º ano' },
{ nome: 'Eduarda Gonçalves Mascarenhas', turma: '8º ano' },
{ nome: 'Felipe Alves de Jesus', turma: '8º ano' },
{ nome: 'Isabella Almeida Tavares Vasconcelos', turma: '8º ano' },
{ nome: 'Jarco Fagundes da Matta Stanesco', turma: '8º ano' },
{ nome: 'Joaquim Gonçalves dos Santos', turma: '8º ano' },
{ nome: 'Liz Adário', turma: '8º ano' },
{ nome: 'Lorena d\'Agosto Calixto', turma: '8º ano' },
{ nome: 'Lorenna Albrusseze Xavier Batista', turma: '8º ano' },
{ nome: 'Marcela Neves Pinheiro Nogueira', turma: '8º ano' },
{ nome: 'Maria Beatriz Felix Gonçalves', turma: '8º ano' },
{ nome: 'Maria Eduarda Valente Gonçalves', turma: '8º ano' },
{ nome: 'Maria Lúcia Garcia Serpa', turma: '8º ano' },
{ nome: 'Maria Sophia Borges de Almeida', turma: '8º ano' },
{ nome: 'Miguel Rocha Di Calafiori', turma: '8º ano' },
{ nome: 'Pedro Barcelos Soares', turma: '8º ano' },

{ nome: 'Alice Barbosa Pecly', turma: '9º ano' },
{ nome: 'Antonella Sabbatini Mello Garcia', turma: '9º ano' },
{ nome: 'Antônio Esteves Flávio', turma: '9º ano' },
{ nome: 'Carolina Batista de Araújo Lima', turma: '9º ano' },
{ nome: 'Caroline Vieira Pereira', turma: '9º ano' },
{ nome: 'Daniela Galiza Costa', turma: '9º ano' },
{ nome: 'Davi Razoni Soares de Souza', turma: '9º ano' },
{ nome: 'Gabriel Coelho de Pádua', turma: '9º ano' },
{ nome: 'Gabriella Corrêa de Aguiar', turma: '9º ano' },
{ nome: 'Giovanna Mendez Leitão', turma: '9º ano' },
{ nome: 'João Marcelo Duarte Lima', turma: '9º ano' },
{ nome: 'Júlia Oliveira Gontijo', turma: '9º ano' },
{ nome: 'Kauan Luís Escudero Castillo', turma: '9º ano' },
{ nome: 'Louise Rangel de Carvalho', turma: '9º ano' },
{ nome: 'Luan Lessa de Moraes', turma: '9º ano' },
{ nome: 'Marcelo Piccoli', turma: '9º ano' },
{ nome: 'Miguel Muniz Pinheiro Nogueira', turma: '9º ano' },
{ nome: 'Nicole Magnusson de Mello', turma: '9º ano' },
{ nome: 'Nitai Moura Brito Naschenveng', turma: '9º ano' },
{ nome: 'Pedro Bolina Assumpção', turma: '9º ano' },
{ nome: 'Rafaela dos Santos Konrad', turma: '9º ano' },
{ nome: 'Rebecca Carrano Rago', turma: '9º ano' },
{ nome: 'Sophia Guimarães Sampaio', turma: '9º ano' },
{ nome: 'Sophia Muniz Barros', turma: '9º ano' },

{ nome: 'Ana Beatriz Oliveira Tavares', turma: '1ª série' },
{ nome: 'Ana Clara Aguiar Franco', turma: '1ª série' },
{ nome: 'Arthur Coutinho Machado', turma: '1ª série' },
{ nome: 'Calebe Rodrigues Fernandes', turma: '1ª série' },
{ nome: 'Davi Cordeiro Pontes', turma: '1ª série' },
{ nome: 'Davi de Assis Aded Coutinho', turma: '1ª série' },
{ nome: 'Davi Dias Caldas', turma: '1ª série' },
{ nome: 'Ester Ferreira Tavares de Campos', turma: '1ª série' },
{ nome: 'Geovana Rodrigues Luz', turma: '1ª série' },
{ nome: 'Gustavo Pereira Gazotti Isaltino', turma: '1ª série' },
{ nome: 'Gustavo Pereira Vieira', turma: '1ª série' },
{ nome: 'Helena Cézar Moulin Fernandes de Souza', turma: '1ª série' },
{ nome: 'Isabela Frechiani Zucolotto Coutinho', turma: '1ª série' },
{ nome: 'Isabele Nayara de Andrade Cruz', turma: '1ª série' },
{ nome: 'Juliana Pedrosa Rodrigues', turma: '1ª série' },
{ nome: 'Lara Montoto Bastos', turma: '1ª série' },
{ nome: 'Laura Tardim Rodrigues', turma: '1ª série' },
{ nome: 'Luíza Tavares de Oliveira Dumas', turma: '1ª série' },
{ nome: 'Maria Beatriz Alexandre dos Santos', turma: '1ª série' },
{ nome: 'Maria Eduarda Vieira Souza Viana', turma: '1ª série' },
{ nome: 'Maria Fernanda Felix Gonçalves', turma: '1ª série' },
{ nome: 'Maria Luísa Gama Costa', turma: '1ª série' },
{ nome: 'Maria Vitória Limas Rodrigues', turma: '1ª série' },
{ nome: 'Mariana Figueiredo Martins', turma: '1ª série' },
{ nome: 'Noahn Souza Ferrazis', turma: '1ª série' },
{ nome: 'Rafael Neves de Souza Toledo', turma: '1ª série' },
{ nome: 'Roberto Avelar Coelho Neto', turma: '1ª série' },
{ nome: 'Samuel Katsuo Yamamoto Amaral', turma: '1ª série' },
{ nome: 'Sofia Barcelos Fragoso', turma: '1ª série' },
{ nome: 'Sophia da Glória Gonçalves', turma: '1ª série' },
{ nome: 'Valentino Mentucci', turma: '1ª série' },
{ nome: 'Vítor Grégio de Araújo Corrêa', turma: '1ª série' },
{ nome: 'Yasmin Sniesko Ribeiro', turma: '1ª série' },

{ nome: 'Ana Clara Amorim Mello', turma: '2ª série' },
{ nome: 'Ana Júlia Carvalho de Souza', turma: '2ª série' },
{ nome: 'Ana Laura Neves Maia', turma: '2ª série' },
{ nome: 'Ana Luíza Rodrigues Machado', turma: '2ª série' },
{ nome: 'André Cozendey Sepúlveda Carvalho', turma: '2ª série' },
{ nome: 'Antônio de Oliveira Sampaio Corrêa', turma: '2ª série' },
{ nome: 'Bernardo Matsumura Nico', turma: '2ª série' },
{ nome: 'Bryan Lucas Silva Santos', turma: '2ª série' },
{ nome: 'Cleyziane Sofie de Andrade Cruz', turma: '2ª série' },
{ nome: 'Henrique Rafael Fraga', turma: '2ª série' },
{ nome: 'João Luiz de Figueiredo Neto', turma: '2ª série' },
{ nome: 'João Pedro Almeida Barbosa da Silveira', turma: '2ª série' },
{ nome: 'Lara Trindade Botelho', turma: '2ª série' },
{ nome: 'Laura Rocha Maia', turma: '2ª série' },
{ nome: 'Letícia Adário', turma: '2ª série' },
{ nome: 'Loreza Melo Nicoli', turma: '2ª série' },
{ nome: 'Maria Caroline Ribeiro dos Santos', turma: '2ª série' },
{ nome: 'Maria Eduarda Almeida Bastos', turma: '2ª série' },
{ nome: 'Maria Eduarda Gonçalves da Silva', turma: '2ª série' },
{ nome: 'Maria Eduarda Patrício Ries', turma: '2ª série' },
{ nome: 'Maria Eduarda Santos de Resende', turma: '2ª série' },
{ nome: 'Maria Eloá Ferreira Silvano de Souza', turma: '2ª série' },
{ nome: 'Marília Gama Costa', turma: '2ª série' },
{ nome: 'Nicolás de Oliveira Pelissari', turma: '2ª série' },
{ nome: 'Rafael Siqueira Pacheco', turma: '2ª série' },
{ nome: 'Serena Santos Rocha Bogado de Almeida', turma: '2ª série' },
{ nome: 'Sofia Reyes Ávila', turma: '2ª série' },
{ nome: 'Victória Lara Wenderroschy Nery', turma: '2ª série' },
{ nome: 'Yasmin Gonçalves Caldeira', turma: '2ª série' },

];

export async function importarAlunos() {
  for (const aluno of alunos) {
    await addDoc(collection(db, 'alunos'), {
      nome: aluno.nome,
      turma: aluno.turma
    });
  }
  console.log('✅ Importação concluída!');
}